#!/bin/sh
if [ $1 = "--help" ]; then
	echo "return media url";
	echo "getmedia [-arg] [source]";
	echo "-i for img";
	echo "-s for sound";
else 
	if [ $1 = "-i" ]; then
		egrep -o '(\/)?(https?:\/\/[a-z0-9]+(\.[a-z0-9]+){1,})?([-0-Za-z\.~\+_]+)?(/[-0-Za-z\.~\+_]+)*\.(jpg|svg|png)' "$2";
	else 
		if [ $1 = "-s" ]; then
			egrep -o '(\/)?(https?:\/\/[a-z0-9]+(\.[a-z0-9]+){1,})?([-0-Za-z\.~\+_]+)?(\/[-0-Za-z\.~\+_]+)*\.(wav|mp3|ogg)' "$2";
		else
			egrep -o '(\/)?(https?:\/\/[a-z0-9]+(\.[a-z0-9]+){1,})?([-0-Za-z\.~\+_]+)?(\/[-0-Za-z\.~\+_]+)*\.(wav|mp3|ogg|jpg|svg|png)' "$1";
		fi
	fi
fi

